apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: centos
spec:
  template:
    metadata:
      name: centos
      labels:
        app: centos
    spec:
      containers:
      - name: centos
        image: uhub.service.ucloud.cn/pingcap/centos-daemon
        securityContext:
            capabilities:
              add:
                - NET_ADMIN
        env:
        - name: PYTHONPATH
          value: "/root/agent"
        ports:
        - containerPort: 8888
          protocol: TCP
          hostPort: 8888
        command: ["/usr/bin/python", "agent"]
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /usr/bin/docker
          name: docker-bin
        - mountPath: /usr/lib64/libltdl.so.7
          name: libltdl
        - mountPath: /host
          name: host-path
        - mountPath: /usr/bin/ip
          name: ip-bin
        - mountPath: /usr/bin/tc
          name: tc-bin
        - mountPath: /root/agent/data
          name: store-data
        - mountPath: /root/agent/logs
          name: log-data
      volumes:
      - name: docker-sock
        hostPath:
           path: /var/run/docker.sock
      - name: docker-bin
        hostPath:
           path: /bin/docker
      - name: libltdl
        hostPath:
          path: /usr/lib64/libltdl.so.7
      - name: host-path
        hostPath:
          path: /
      - name: ip-bin
        hostPath:
          path: /sbin/ip
      - name: tc-bin
        hostPath:
          path: /sbin/tc
      - name: store-data
        hostPath:
          path: /tmp/data
      - name: log-data
        hostPath:
          path: /tmp/logs


#-v /:/host -v $(which ip):/usr/bin/ip -v $(which tc):/usr/bin/tc -v /tmp/data:/root/agent/data